#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Thu May 26 17:19:19 EDT 2022
# SW Build 3064766 on Wed Nov 18 09:12:47 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim simul_module_sig_tb_behav -key {Behavioral:sim_1:Functional:simul_module_sig_tb} -tclbatch simul_module_sig_tb.tcl -protoinst "protoinst_files/design_1.protoinst" -view /mnt/home/gegi/usager/grem3208/Bureau/S4APP2main/new/pb_logique_seq/simul_module_sig_tb_behav.wcfg -log simulate.log"
xsim simul_module_sig_tb_behav -key {Behavioral:sim_1:Functional:simul_module_sig_tb} -tclbatch simul_module_sig_tb.tcl -protoinst "protoinst_files/design_1.protoinst" -view /mnt/home/gegi/usager/grem3208/Bureau/S4APP2main/new/pb_logique_seq/simul_module_sig_tb_behav.wcfg -log simulate.log

